import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';
pdfMake.vfs = pdfFonts.vfs;
import Format from '../Utils/Format';
import DateUtility from '../Utils/DateUtils';




const styles = {
  header: {
    marginTop: 5,
    fontSize: 28,
  },
  subHeading: {
    fontSize: 22
  },
  row: {
    fontSize: 16
  },
  rowNumber: {
    fontSize: 16,
    alignment: "right",
    marginRight: 10,
    marginLeft: 10 
  },
  rowCurrency: {
    fontSize: 16,
    alignment: "right"
  },
  footer: {
    fontSize: 10,
    alignment: 'center'
  },
  datePickerSingle: {
    fontSize: 14,
    marginTop: 15,
    alignment: "center"
  },
  datePickerMultiL: {
    fontSize: 14,
    alignment: "right"
  },
  datePickerMultiR: {
    fontSize: 14,
    alignment: "left"
  },
  datePickerMultiC: {
    fontSize: 12,
    alignment: "center"
  }
}

const LETTER_WIDTH = 595.28;

const drawLine = (width,stroke=1) => {
  return {
    svg: `<svg width="${width}" height="${stroke}">z
            <line x1="0" y1="0" x2="${width}" y2="0" stroke="black" stroke-width="${stroke}"/>
          </svg>`
  }
}

const generateDateRange = (dateRange) => {
  if (DateUtility.isEqual(dateRange.startDate,dateRange.endDate)){
    return {text: Format.asLongDate(dateRange.endDate),style:"datePickerSingle"}
  }
  return {
    marginTop: 15,
    columns: [
      {width:'*',text: Format.asLongDate(dateRange.startDate),style:"datePickerMultiL"},
      {width:'*',text: "through",style:"datePickerMultiC"},
      {width:'*',text: Format.asLongDate(dateRange.endDate),style:"datePickerMultiR"},
    ]
  }
}

function createSalesReport(creator,storeName,dateRange,data,options){

  const generateRows = () => {
    return data.map(row => {
      return [
        {
          text:row.description,
          style: "row"
        },
        {
          text:Format.string(parseInt(row.quantity),Format.NUMBER_FORMAT),
          style: "rowNumber"
        },
        {
          text:Format.string(row.total,Format.CURRENCY_FORMAT),
          style: "rowCurrency"
        }
      ]
    })
  }

  const documentDef = {
    pageSize: 'LETTER',
    pageMargins: [ 20, 20, 20, 20 ],
    header: {marginTop:5,text: `Generated by: ${creator} with GLDS Pocket Reports`,fontSize:10,alignment:'center'},
        footer: {text: `Generated on: 02/06/2026`,style:'footer'},
        content: [
          {text: "Store Sales Report",style:'header'},
          {text: storeName,style:'subHeading'},
          generateDateRange(dateRange),
          drawLine(LETTER_WIDTH - 20),
          {
            margin: [5,0,5,0],
            layout: "noBorders",
            table: {
              widths: ['*','auto','auto'],
              body: generateRows()
            }
          },
          drawLine(LETTER_WIDTH - 20)
        ],
        styles: styles
  }

  // pdfMake.createPdf(documentDef).download('StoreSalesReport.pdf');
  // pdfMake.createPdf(documentDef).open();
  // pdfMake.createPdf(documentDef).save('StoreSalesReport.pdf');
  pdfMake.createPdf(documentDef).getDataUrl().then((blob) => {
    let tmp = blob;
    debugger;
  },err => {
    console.error(err.message);
  })
}

function createSalesTenderReport(creator,storeName,dateRange,data,options){
  const generateRows = () => {
    return data.map(row => {
      return [
        {
          text:row.description,
          style: "row"
        },
        {
          text:Format.string(parseInt(row.quantity),Format.NUMBER_FORMAT),
          style: "rowNumber"
        },
        {
          text:Format.string(row.total,Format.CURRENCY_FORMAT),
          style: "rowCurrency"
        }
      ]
    })
  }

  const documentDef = {
    pageSize: 'LETTER',
    pageMargins: [ 20, 20, 20, 20 ],
    header: {marginTop:5,text: `Generated by: ${creator} with GLDS Pocket Reports`,fontSize:10,alignment:'center'},
        footer: {text: `Generated on: 02/06/2026`,style:'footer'},
        content: [
          {text: "Tender Sales Report",style:'header'},
          {text: storeName,style:'subHeading'},
          generateDateRange(dateRange),
          drawLine(LETTER_WIDTH - 20),
          {
            margin: [5,0,5,0],
            layout: "headerLineOnly",
            table: {
              widths: ['*','auto','auto'],
              body: generateRows()
            }
          },
          drawLine(LETTER_WIDTH - 20),
          {
            columns: [
              {
                fontSize:18,
                bold: true,
                text: "Total"
              },
              {
                fontSize:18,
                bold: true,
                alignment: "right",
                text: Format.string(data.reduce((acc,cur) => {
                  return acc + cur.total;
                },0.00),Format.CURRENCY_FORMAT)
              },
            ]
          }
          
        ],
        styles: styles
  }

  pdfMake.createPdf(documentDef).download('TenderSalesReport.pdf');
}

export {
  createSalesReport,
  createSalesTenderReport
}