import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';
pdfMake.vfs = pdfFonts.vfs;
import Format from '../Utils/Format';
import DateUtility from '../Utils/DateUtils';

pdfMake.fonts = {
  Roboto: {
    normal: "Roboto-Regular.ttf",
    italics: "Roboto-Italic.ttf",
    bolditalics: "Roboto-MediumItalic.ttf",
    bold: "Roboto-Medium.ttf"
  }
}




const styles = {
  header: {
    marginTop: 5,
    fontSize: 28,
    bold: true
  },
  tableHeader: { bold: true, color: 'white', fontSize: 11 },
  subHeading: {
    font: "Roboto",
    fontSize: 22
  },
  row: {
    fontSize: 16
  },
  rowNumber: {
    fontSize: 16,
    alignment: "right",
    marginRight: 10,
    marginLeft: 10 
  },
  rowCurrency: {
    fontSize: 16,
    alignment: "right"
  },
  footer: {
    fontSize: 10,
    alignment: 'center'
  },
  datePickerSingle: {
    fontSize: 14,
    marginTop: 15,
    alignment: "center"
  },
  datePickerMultiL: {
    fontSize: 14,
    alignment: "right"
  },
  datePickerMultiR: {
    fontSize: 14,
    alignment: "left"
  },
  datePickerMultiC: {
    fontSize: 12,
    alignment: "center"
  }
}

const LETTER_WIDTH = 595.28;

const drawLine = (width,stroke=1) => {
  return { canvas: [{ type: 'line', x1: 0, y1: 5, x2: width, y2: 5, lineWidth: 1.5, lineColor: '#3182ce' }], margin: [0, 0, 0, 20] }
}

const generateDateRange = (dateRange) => {
  if (DateUtility.isEqual(dateRange.startDate,dateRange.endDate)){
    return {text: Format.asLongDate(dateRange.endDate),style:"datePickerSingle"}
  }
  return {
    marginTop: 15,
    columns: [
      {width:'*',text: Format.asLongDate(dateRange.startDate),style:"datePickerMultiL"},
      {width:'*',text: "through",style:"datePickerMultiC"},
      {width:'*',text: Format.asLongDate(dateRange.endDate),style:"datePickerMultiR"},
    ]
  }
}

function createSalesReport(creator,storeName,dateRange,data,options){

  const generateRows = () => {
    const tableBody = [// header row
      [
        { text: 'Description', style: 'tableHeader' },
        { text: 'Quantity',    style: 'tableHeader', alignment: 'center' },
        { text: 'Total',       style: 'tableHeader', alignment: 'right'  }
      ]
    ];
    data.forEach(item => {
      tableBody.push([
        { text: item.description },
        { text: Format.string(parseInt(item.quantity),Format.NUMBER_FORMAT), alignment: 'center' },
        { text: Format.string(item.total,Format.CURRENCY_FORMAT), alignment: 'right' }
      ]);
    });
    // // Grand total row
    // tableBody.push([
    //   { text: 'Grand Total', colSpan: 2, bold: true,fontSize:16, fillColor: '#dbeafe', color: '#1e40af' },
    //   {},
    //   { text: Format.string(Format.string(data.reduce((acc,cur) => {
    //                return acc + cur.total;},0.00)),Format.CURRENCY_FORMAT),fontSize:16, bold: true, alignment: 'right', fillColor: '#dbeafe', color: '#1e40af' }
    // ]);
    return tableBody
  }

  const documentDef = {
    pageSize: 'LETTER',
    pageMargins: [ 20, 20, 20, 20 ],
    header: {marginTop:5,text: `Generated by: ${creator} with GLDS Pocket Reports`,fontSize:10,alignment:'center'},
        footer: {text: `Generated on: 02/06/2026`,style:'footer'},
        content: [
          {text: "Store Sales Report",style:'header'},
          {text: storeName,style:'subHeading'},
          generateDateRange(dateRange),
          drawLine(LETTER_WIDTH - 20),
          {
            // margin: [5,0,5,0],
            layout: "headerLineOnly",
            table: {
              headerRows: 1,
              widths: ['*', 80, 100],
              body: generateRows()
            },
            layout: {
              fillColor: (rowIndex) => rowIndex === 0 ? '#2d3748' : (rowIndex % 2 === 0 ? '#f7fafc' : null),
              hLineWidth: () => 0,
              vLineWidth: () => 0,
              hLineColor: () => '#e2e8f0',
              paddingLeft: () => 5,
              paddingRight: () => 5,
              paddingTop: () => 8,
              paddingBottom: () => 8,
            }
          },
          drawLine(LETTER_WIDTH - 20)
        ],
        styles: styles
  }

  // pdfMake.createPdf(documentDef).download('StoreSalesReport.pdf');
  // pdfMake.createPdf(documentDef).open();
  pdfMake.createPdf(documentDef).print();
  // pdfMake.createPdf(documentDef).save('StoreSalesReport.pdf');
  // pdfMake.createPdf(documentDef).getDataUrl().then((blob) => {
  //   let tmp = blob;
  //   
  // },err => {
  //   console.error(err.message);
  // })
}

function createSalesTenderReport(creator,storeName,dateRange,data,options){

  const generateRows = () => {
    const tableBody = [// header row
      [
        { text: 'Description', style: 'tableHeader' },
        { text: 'Quantity',    style: 'tableHeader', alignment: 'center' },
        { text: 'Total',       style: 'tableHeader', alignment: 'right'  }
      ]
    ];
    data.forEach(item => {
      tableBody.push([
        { text: item.description },
        { text: Format.string(parseInt(item.quantity),Format.NUMBER_FORMAT), alignment: 'center' },
        { text: Format.string(item.total,Format.CURRENCY_FORMAT), alignment: 'right' }
      ]);
    });
    // Grand total row
    tableBody.push([
      { text: 'Grand Total', colSpan: 2, bold: true,fontSize:16, fillColor: '#dbeafe', color: '#1e40af' },
      {},
      { text: Format.string(Format.string(data.reduce((acc,cur) => {
                   return acc + cur.total;},0.00)),Format.CURRENCY_FORMAT),fontSize:16, bold: true, alignment: 'right', fillColor: '#dbeafe', color: '#1e40af' }
    ]);
    return tableBody
  }

  const documentDef = {
    pageSize: 'LETTER',
    pageMargins: [ 20, 20, 20, 20 ],
    header: {marginTop:5,text: `Generated by: ${creator} with GLDS Pocket Reports`,fontSize:10,alignment:'center'},
        footer: {text: `Generated on: 02/06/2026`,style:'footer'},
        content: [
          {text: "Tender Sales Report",style:'header'},
          {text: storeName,style:'subHeading'},
          generateDateRange(dateRange),
          drawLine(LETTER_WIDTH - 20),
          {
            // margin: [5,0,5,0],
            layout: "headerLineOnly",
            table: {
              headerRows: 1,
              widths: ['*', 80, 100],
              body: generateRows()
            },
            layout: {
              fillColor: (rowIndex) => rowIndex === 0 ? '#2d3748' : (rowIndex % 2 === 0 ? '#f7fafc' : null),
              hLineWidth: () => 0,
              vLineWidth: () => 0,
              hLineColor: () => '#e2e8f0',
              paddingLeft: () => 10,
              paddingRight: () => 10,
              paddingTop: () => 8,
              paddingBottom: () => 8,
            }
          },
        ],
        styles: styles
  }

  pdfMake.createPdf(documentDef).print();
}
// function createSalesTenderReport(creator,storeName,dateRange,data,options){
//   const generateRows = () => {
//     return data.map(row => {
//       return [
//         {
//           text:row.description,
//           style: "row"
//         },
//         {
//           text:Format.string(parseInt(row.quantity),Format.NUMBER_FORMAT),
//           style: "rowNumber"
//         },
//         {
//           text:Format.string(row.total,Format.CURRENCY_FORMAT),
//           style: "rowCurrency"
//         }
//       ]
//     })
//   }

//   const documentDef = {
//     pageSize: 'LETTER',
//     pageMargins: [ 20, 20, 20, 20 ],
//     header: {marginTop:5,text: `Generated by: ${creator} with GLDS Pocket Reports`,fontSize:10,alignment:'center'},
//         footer: {text: `Generated on: 02/06/2026`,style:'footer'},
//         content: [
//           {text: "Tender Sales Report",style:'header'},
//           {text: storeName,style:'subHeading'},
//           generateDateRange(dateRange),
//           drawLine(LETTER_WIDTH - 20),
//           {
//             margin: [5,0,5,0],
//             layout: "headerLineOnly",
//             table: {
//               widths: ['*','auto','auto'],
//               body: generateRows()
//             }
//           },
//           drawLine(LETTER_WIDTH - 20),
//           {
//             columns: [
//               {
//                 fontSize:18,
//                 bold: true,
//                 text: "Total"
//               },
//               {
//                 fontSize:18,
//                 bold: true,
//                 alignment: "right",
//                 text: Format.string(data.reduce((acc,cur) => {
//                   return acc + cur.total;
//                 },0.00),Format.CURRENCY_FORMAT)
//               },
//             ]
//           }
          
//         ],
//         styles: styles
//   }

//   pdfMake.createPdf(documentDef).print();
// }

export {
  createSalesReport,
  createSalesTenderReport
}